language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: kegan+isogon@keganmyers.com
  api_key:
    secure: NeBt5LVjYWRBbyDaupXwkNs6+Kb8Efnsuf8S8E60FD42vaXzgBdNfO8Jdpm0w6uy6E6NUVhfb7V3hh/+l8miq65KJslDsGPMbnXsFDRurTCfy0lLL9MNFtNdz6xSXyARFZJindzvxEdvybKc91X+m8NXHwivdKlvOdjdrjzRafnus32fpSRUlLAOwF+/cyyeMvAblxeMKcC0cAZ0FLjxBxMRLOxZWAi1MaK5oZhioJExwNZj2QnCxg58oOSWAJlFyCH8vorlYFzfjVTpCHxZg9//04ZF669lmdjaHGzrp55qA3TcatETIidXbm5o0mkUq6kYk6CtBZCqcRZ6RmvVtdsG21sGh6n5t62oe29+krCg07mdBu72/bU9/Z3RChKEHVu/sLsLtKBWnb3m9QZwPUKZ1aFKgloC+6PpHss7YvXKZQtNFnzHVPVD9t0J1LcgC9n9sm66bS7p8UmwXe5gdWSr/4lE9uRMV3ITJ9Kf8zd7Ey+XDIqA1Wij2DzYliadSLbfVYAKz6bqtWbvK55xrCtkf+0Elzs5X0cK7HMAIgEQq+7Gze9BHt6+G5u/wXRIblWgQ0c7iSz2ljDqqg/CQ9KHu5J5Mz6Pd34hFApKPNWojDW9F2FcQrzac45pBl1i2Gw8WXhLkwm9w9TRVIBpP/tjStMPxZ/ThGBO5Y3ORGo=
  skip_cleanup: true
  on:
    tags: true
    repo: isogon/eslint-config
